"""
expanded_gold_trials.py — v1.5 Expanded Corpus Validation
==========================================================
Runs km_pipeline on trials and compares HR extraction against ground truth.

Trial sets:
  - Original: 13 AF-ablation gold trials
  - Cardio: 12 diverse cardio/metabolic trials
  - Phase 2: 15 new diverse trials (5 specialties x 3)
  - Phase 4: 95 new trials (7 specialties, loaded from JSON)

Therapeutic areas (7+):
  - Cardiac ablation (AF): 13 original gold trials
  - Heart failure, obesity, AF/CAD, TAVR, AF/ACS, AF/PCI
  - Diabetes, Oncology, Respiratory, Neurology, Infectious
  - Cardiology, Rheumatology (Phase 4)
"""

import os
import sys
import io
import json
import time
import platform
from pathlib import Path
from datetime import datetime, timezone

# WORKAROUND: Python 3.13 on Windows — WMI COM interface deadlocks when
# platform._wmi_query() is called (triggered by scipy → numpy.testing →
# platform.machine()). Raise OSError so callers use their built-in fallbacks.
if sys.platform == 'win32':
    def _safe_wmi_query(*args, **kwargs):
        raise OSError("WMI bypassed to avoid Python 3.13 deadlock")
    platform._wmi_query = _safe_wmi_query

# Add wasserstein dir to path
WASSERSTEIN_DIR = Path(__file__).parent
sys.path.insert(0, str(WASSERSTEIN_DIR))

from km_pipeline import KMPipeline, _safe_stem, write_summary_json

# ---------------------------------------------------------------------------
# PDF directories
# ---------------------------------------------------------------------------
ABLATION_DIR = Path(r"C:\Users\user\Downloads\Ablation")
DOWNLOADS_DIR = Path(r"C:\Users\user\Downloads")
ONCOLOGY_DIR = Path(r"C:\Users\user\oncology_rcts")
DIABETES_DIR = Path(r"C:\Users\user\diabetes_rcts")
RESPIRATORY_DIR = Path(r"C:\Users\user\respiratory_rcts")
NEUROLOGY_DIR = Path(r"C:\Users\user\neurology_rcts")
INFECTIOUS_DIR = Path(r"C:\Users\user\infectious_rcts")
CARDIOLOGY_DIR = Path(r"C:\Users\user\cardiology_rcts")
RHEUMATOLOGY_DIR = Path(r"C:\Users\user\rheumatology_rcts")

# Phase 4 trials JSON (generated by select_diverse_trials.py)
PHASE4_JSON = WASSERSTEIN_DIR / "selected_phase4_trials.json"

# ---------------------------------------------------------------------------
# Original 13 ablation trials (from regression_validate_13.py)
# ---------------------------------------------------------------------------
ORIGINAL_TRIALS = [
    {
        "name": "HUNTER",
        "pdf": "Cardiovasc electrophysiol - 2015 - HUNTER - Point\u2010by\u2010Point Radiofrequency Ablation Versus the Cryoballoon or a Novel.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.53, "gt_ci_lower": 0.25, "gt_ci_upper": 1.1,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "MILILIS-PERS",
        "pdf": "Cardiovasc electrophysiol - 2023 - Mililis - Radiofrequency versus cryoballoon catheter ablation in patients with.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.96, "gt_ci_lower": 0.5, "gt_ci_upper": 1.8,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "FIRE AND ICE",
        "pdf": "NEJMoa1602014.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.96, "gt_ci_lower": 0.76, "gt_ci_upper": 1.22,
        "hr_source": "reported", "area": "AF-ablation",
    },
    {
        "name": "CIRCA-DOSE",
        "pdf": "andrade-et-al-cryoballoon-or-radiofrequency-ablation-for-atrial-fibrillation-assessed-by-continuous-monitoring.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 1.08, "gt_ci_lower": 0.78, "gt_ci_upper": 1.5,
        "hr_source": "reported", "area": "AF-ablation",
    },
    {
        "name": "FROZEN AF",
        "pdf": "chun-et-al-cryoballoon-versus-laserballoon.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.9, "gt_ci_lower": 0.5, "gt_ci_upper": 1.6,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "CRRF-PeAF",
        "pdf": "ehaf451.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.99, "gt_ci_lower": 0.69, "gt_ci_upper": 1.43,
        "hr_source": "reported", "area": "AF-ablation",
    },
    {
        "name": "HIPAF",
        "pdf": "euaf066.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 1.47, "gt_ci_lower": 0.7, "gt_ci_upper": 2.5,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "PVAC-CPVI",
        "pdf": "eut398.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.72, "gt_ci_lower": 0.35, "gt_ci_upper": 1.5,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "WACA-PVAC",
        "pdf": "euu064.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 1.14, "gt_ci_lower": 0.6, "gt_ci_upper": 2.1,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "CRAVE",
        "pdf": "pak-et-al-cryoballoon-versus-high-power-short-duration-radiofrequency-ablation-for-pulmonary-vein-isolation-in-patients.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.91, "gt_ci_lower": 0.45, "gt_ci_upper": 1.85,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "ADVENT",
        "pdf": "reddy-et-al-pulsed-field-vs-conventional-thermal-ablation-for-paroxysmal-atrial-fibrillation.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.92, "gt_ci_lower": 0.55, "gt_ci_upper": 1.5,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "FREEZEAF-30M",
        "pdf": "s12872-017-0566-6.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 1.06, "gt_ci_lower": 0.55, "gt_ci_upper": 2.0,
        "hr_source": "derived", "area": "AF-ablation",
    },
    {
        "name": "LBRF-PERSISTENT",
        "pdf": "schmidt-et-al-laser-balloon-or-wide-area-circumferential-irrigated-radiofrequency-ablation-for-persistent-atrial.pdf",
        "pdf_dir": "ablation",
        "gt_hr": 0.93, "gt_ci_lower": 0.5, "gt_ci_upper": 1.7,
        "hr_source": "derived", "area": "AF-ablation",
    },
]

# ---------------------------------------------------------------------------
# 12 diverse cardiology/metabolic trials (from v1.2)
# ---------------------------------------------------------------------------
CARDIO_TRIALS = [
    {
        "name": "EMPEROR-Preserved",
        "pdf": "NEJMoa2107038.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.79, "gt_ci_lower": 0.69, "gt_ci_upper": 0.90,
        "hr_source": "reported", "area": "heart-failure",
        "n_arms": 2,
    },
    {
        "name": "DELIVER",
        "pdf": "NEJMoa2206286.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.82, "gt_ci_lower": 0.73, "gt_ci_upper": 0.92,
        "hr_source": "reported", "area": "heart-failure",
        "n_arms": 2,
    },
    {
        "name": "SELECT",
        "pdf": "NEJMoa2307563.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.80, "gt_ci_lower": 0.72, "gt_ci_upper": 0.90,
        "hr_source": "reported", "area": "obesity-CV",
        "n_arms": 2,
    },
    {
        "name": "AFIRE",
        "pdf": "NEJMoa1904143.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.72, "gt_ci_lower": 0.55, "gt_ci_upper": 0.95,
        "hr_source": "reported", "area": "AF-CAD",
        "n_arms": 2,
    },
    {
        "name": "PARTNER 3",
        "pdf": "Partner3.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.54, "gt_ci_lower": 0.37, "gt_ci_upper": 0.79,
        "hr_source": "reported", "area": "TAVR",
        "n_arms": 2,
    },
    {
        "name": "AUGUSTUS",
        "pdf": "Augustus.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.69, "gt_ci_lower": 0.58, "gt_ci_upper": 0.81,
        "hr_source": "reported", "area": "AF-ACS",
        "n_arms": 2,
    },
    {
        "name": "SHIFT",
        "pdf": "IvabradineandoutcomesinchronicheartfailureSHIFT-arandomisedplacebo-controlledstudy.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.82, "gt_ci_lower": 0.75, "gt_ci_upper": 0.90,
        "hr_source": "reported", "area": "heart-failure",
        "n_arms": 2,
    },
    {
        "name": "MERIT-HF",
        "pdf": "EffectofmetoprololCR-XLinchronicheartfailure.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.66, "gt_ci_lower": 0.53, "gt_ci_upper": 0.81,
        "hr_source": "reported", "area": "heart-failure",
        "n_arms": 2,
    },
    {
        "name": "ENTRUST-AF PCI",
        "pdf": "entrust.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.83, "gt_ci_lower": 0.65, "gt_ci_upper": 1.05,
        "hr_source": "reported", "area": "AF-PCI",
        "n_arms": 2,
    },
    {
        "name": "PIONEER AF-PCI",
        "pdf": "Pioneer AF.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.59, "gt_ci_lower": 0.47, "gt_ci_upper": 0.76,
        "hr_source": "reported", "area": "AF-PCI",
        "n_arms": 3,
    },
    {
        "name": "ADVANCE",
        "pdf": "NEJMoa0802987.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.90, "gt_ci_lower": 0.82, "gt_ci_upper": 0.98,
        "hr_source": "reported", "area": "diabetes",
        "n_arms": 2,
    },
    {
        "name": "CIBIS-II",
        "pdf": "TheLancet1999Investigators.pdf",
        "pdf_dir": "downloads",
        "gt_hr": 0.66, "gt_ci_lower": 0.54, "gt_ci_upper": 0.81,
        "hr_source": "reported", "area": "heart-failure",
        "n_arms": 2,
    },
]

# ---------------------------------------------------------------------------
# Phase 2: 15 new diverse trials (3 per specialty)
# ---------------------------------------------------------------------------
PHASE2_TRIALS = [
    # Oncology (3)
    {
        "name": "PMC10115555",
        "pdf": "PMC10115555.pdf",
        "pdf_dir": "oncology",
        "gt_hr": 0.82, "gt_ci_lower": 0.69, "gt_ci_upper": 0.97,
        "hr_source": "reported", "area": "oncology",
    },
    {
        "name": "PMC10427418",
        "pdf": "PMC10427418.pdf",
        "pdf_dir": "oncology",
        "gt_hr": 0.678, "gt_ci_lower": 0.546, "gt_ci_upper": 0.841,
        "hr_source": "reported", "area": "oncology",
    },
    {
        "name": "PMC10553121",
        "pdf": "PMC10553121.pdf",
        "pdf_dir": "oncology",
        "gt_hr": 0.73, "gt_ci_lower": 0.62, "gt_ci_upper": 0.86,
        "hr_source": "reported", "area": "oncology",
        "outcome_type": "OS",
    },
    # Diabetes (3) — SUSTAIN-6 is gold, others are silver
    {
        "name": "SUSTAIN-6",
        "pdf": "PMC11943310.pdf",
        "pdf_dir": "oncology",  # stored in oncology_rcts dir
        "gt_hr": 0.74, "gt_ci_lower": 0.58, "gt_ci_upper": 0.95,
        "hr_source": "reported", "area": "diabetes",
    },
    {
        "name": "SGLT2-insulin",
        "pdf": "40036884_Effects of SGLT2 inhibition on insulin u.pdf",
        "pdf_dir": "diabetes",
        "gt_hr": 0.81, "gt_ci_lower": 0.71, "gt_ci_upper": 0.93,
        "hr_source": "reported", "area": "diabetes",
    },
    {
        "name": "SGLT2-nonDM",
        "pdf": "40978864_Sodium-Glucose Cotransporter 2 SGLT2 Inh.pdf",
        "pdf_dir": "diabetes",
        "gt_hr": 0.73, "gt_ci_lower": 0.6, "gt_ci_upper": 0.88,
        "hr_source": "reported", "area": "diabetes",
    },
    # Respiratory (3)
    {
        "name": "PMC10323201",
        "pdf": "PMC10323201.pdf",
        "pdf_dir": "respiratory",
        "gt_hr": 0.62, "gt_ci_lower": 0.38, "gt_ci_upper": 0.99,
        "hr_source": "reported", "area": "respiratory",
    },
    {
        "name": "PMC10952210",
        "pdf": "PMC10952210.pdf",
        "pdf_dir": "respiratory",
        "gt_hr": 0.32, "gt_ci_lower": 0.14, "gt_ci_upper": 0.76,
        "hr_source": "reported", "area": "respiratory",
    },
    {
        "name": "PMC10990610",
        "pdf": "PMC10990610.pdf",
        "pdf_dir": "respiratory",
        "gt_hr": 0.66, "gt_ci_lower": 0.53, "gt_ci_upper": 0.83,
        "hr_source": "reported", "area": "respiratory",
        "outcome_type": "PFS",
    },
    # Neurology (3)
    {
        "name": "PMC10805160",
        "pdf": "PMC10805160.pdf",
        "pdf_dir": "neurology",
        "gt_hr": 0.59, "gt_ci_lower": 0.54, "gt_ci_upper": 0.64,
        "hr_source": "reported", "area": "neurology",
    },
    {
        "name": "PMC11296275",
        "pdf": "PMC11296275.pdf",
        "pdf_dir": "neurology",
        "gt_hr": 0.69, "gt_ci_lower": 0.57, "gt_ci_upper": 0.83,
        "hr_source": "reported", "area": "neurology",
        "outcome_type": "PFS",
    },
    {
        "name": "PMC11448330",
        "pdf": "PMC11448330.pdf",
        "pdf_dir": "neurology",
        "gt_hr": 0.8, "gt_ci_lower": 0.61, "gt_ci_upper": 1.05,
        "hr_source": "reported", "area": "neurology",
    },
    # Infectious (3)
    {
        "name": "PMC10052578",
        "pdf": "PMC10052578.pdf",
        "pdf_dir": "infectious",
        "gt_hr": 0.69, "gt_ci_lower": 0.56, "gt_ci_upper": 0.85,
        "hr_source": "reported", "area": "infectious",
        "outcome_type": "PFS",
    },
    {
        "name": "PMC10105623",
        "pdf": "PMC10105623.pdf",
        "pdf_dir": "infectious",
        "gt_hr": 0.35, "gt_ci_lower": 0.24, "gt_ci_upper": 0.51,
        "hr_source": "reported", "area": "infectious",
    },
    {
        "name": "PMC11103724",
        "pdf": "PMC11103724.pdf",
        "pdf_dir": "infectious",
        "gt_hr": 0.33, "gt_ci_lower": 0.26, "gt_ci_upper": 0.43,
        "hr_source": "reported", "area": "infectious",
    },
]

ALL_TRIALS = ORIGINAL_TRIALS + CARDIO_TRIALS + PHASE2_TRIALS
OUTPUT_DIR = WASSERSTEIN_DIR / "expanded_40_results"

# Directory map for pdf_dir field
PDF_DIR_MAP = {
    "ablation": ABLATION_DIR,
    "downloads": DOWNLOADS_DIR,
    "oncology": ONCOLOGY_DIR,
    "diabetes": DIABETES_DIR,
    "respiratory": RESPIRATORY_DIR,
    "neurology": NEUROLOGY_DIR,
    "infectious": INFECTIOUS_DIR,
    "cardiology": CARDIOLOGY_DIR,
    "rheumatology": RHEUMATOLOGY_DIR,
}


def load_phase4_trials():
    """Load Phase 4 trials from JSON generated by select_diverse_trials.py."""
    if not PHASE4_JSON.exists():
        print(f"WARNING: Phase 4 trials not found: {PHASE4_JSON}")
        print("  Run: python select_diverse_trials.py")
        return []
    with open(PHASE4_JSON, 'r', encoding='utf-8') as f:
        trials = json.load(f)
    # Validate required fields
    valid = []
    for t in trials:
        required = ('name', 'pdf', 'pdf_dir', 'gt_hr',
                    'gt_ci_lower', 'gt_ci_upper')
        if all(k in t for k in required):
            # Default hr_source if missing
            if 'hr_source' not in t:
                t['hr_source'] = 'unknown'
            if 'area' not in t:
                t['area'] = t.get('pdf_dir', 'unknown')
            valid.append(t)
    return valid


def get_pdf_path(trial):
    """Resolve PDF path based on pdf_dir field."""
    d = PDF_DIR_MAP.get(trial.get("pdf_dir"), DOWNLOADS_DIR)
    return d / trial["pdf"]


def categorize_result(result):
    """Assign failure category to a result dict."""
    status = result["status"]
    if status in ("FAIL_EXTRACT", "EXCEPTION"):
        return "FAIL_EXTRACT"
    if not result.get("within_ci"):
        return "FAIL_ACCURACY"
    method = result.get("hr_method", "")
    if "text_derived_only" in str(method):
        return "TEXT_ONLY"
    rel_err = result.get("rel_error_pct")
    if rel_err is not None and rel_err >= 10.0:
        return "MARGINAL"
    return "PASS"


def validate_trial(pipeline, trial, trial_idx, total):
    """Run extraction on one trial and return result dict."""
    pdf_path = get_pdf_path(trial)
    name = trial["name"]
    gt_hr = trial["gt_hr"]
    gt_lo = trial["gt_ci_lower"]
    gt_hi = trial["gt_ci_upper"]
    area = trial.get("area", "unknown")

    print(f"\n[{trial_idx}/{total}] {name} ({area})")
    print(f"  PDF: {trial['pdf'][:65]}...")
    print(f"  Ground Truth: HR={gt_hr} [{gt_lo}, {gt_hi}]")

    target_endpoint = trial.get("outcome_type")
    t0 = time.time()
    try:
        result = pipeline.extract(str(pdf_path),
                                  target_endpoint=target_endpoint)
        elapsed = time.time() - t0

        if result.succeeded and result.hr is not None:
            ext_hr = result.hr
            ext_lo = result.ci_lower
            ext_hi = result.ci_upper

            # Check: extracted HR within ground truth CI?
            within_ci = gt_lo <= ext_hr <= gt_hi

            # Reciprocal fallback ONLY for derived-HR trials
            recip_hr = None
            within_ci_recip = False
            if trial.get("hr_source") == "derived" and ext_hr > 0:
                recip_hr = 1.0 / ext_hr
                within_ci_recip = gt_lo <= recip_hr <= gt_hi

            # Use whichever orientation is closer to GT
            if gt_hr == 0:
                rel_error = float('inf') if ext_hr != 0 else 0.0
                orientation = "direct"
                final_hr = ext_hr
            elif not within_ci and within_ci_recip:
                rel_error = abs(recip_hr - gt_hr) / gt_hr * 100
                orientation = "reciprocal"
                final_hr = recip_hr
            else:
                rel_error = abs(ext_hr - gt_hr) / gt_hr * 100
                orientation = "direct"
                final_hr = ext_hr

            within_ci_final = gt_lo <= final_hr <= gt_hi

            status = "PASS" if within_ci_final else "FAIL"
            error_ok = rel_error < 10.0

            ci_str = (f"[{ext_lo:.3f}, {ext_hi:.3f}]"
                      if ext_lo is not None and ext_hi is not None
                      else "[N/A]")
            print(f"  Extracted: HR={ext_hr:.3f} {ci_str}")
            if orientation == "reciprocal":
                print(f"  Reciprocal: HR={recip_hr:.3f} (better match)")
            print(f"  Rel Error: {rel_error:.1f}% {'OK' if error_ok else '>10%'}")
            print(f"  Within CI: {within_ci_final} -> {status}")
            print(f"  Method: {result.hr_method}")
            print(f"  Time: {elapsed:.1f}s  IPD: {result.total_ipd_records}")

            # Save per-trial summary
            stem = _safe_stem(trial["pdf"])
            write_summary_json(result, str(OUTPUT_DIR / f"{stem}_summary.json"))

            return {
                "name": name,
                "pdf": trial["pdf"],
                "area": area,
                "gt_hr": gt_hr,
                "gt_ci": [gt_lo, gt_hi],
                "ext_hr": ext_hr,
                "ext_ci": [ext_lo, ext_hi],
                "final_hr": final_hr,
                "orientation": orientation,
                "rel_error_pct": round(rel_error, 2),
                "within_ci": within_ci_final,
                "error_under_10pct": error_ok,
                "ipd_records": result.total_ipd_records,
                "time_s": round(elapsed, 1),
                "status": status,
                "n_curves_found": result.n_curves_found,
                "hr_method": result.hr_method,
            }
        else:
            elapsed = time.time() - t0
            warnings = result.warnings if result.warnings else ["Unknown failure"]
            print(f"  FAILED: {warnings[0]}")
            print(f"  Time: {elapsed:.1f}s")
            return {
                "name": name,
                "pdf": trial["pdf"],
                "area": area,
                "gt_hr": gt_hr,
                "ext_hr": None,
                "within_ci": False,
                "error_under_10pct": False,
                "time_s": round(elapsed, 1),
                "status": "FAIL_EXTRACT",
                "error": warnings[0],
            }

    except Exception as e:
        elapsed = time.time() - t0
        print(f"  EXCEPTION: {e}")
        print(f"  Time: {elapsed:.1f}s")
        return {
            "name": name,
            "pdf": trial["pdf"],
            "area": area,
            "gt_hr": gt_hr,
            "ext_hr": None,
            "within_ci": False,
            "error_under_10pct": False,
            "time_s": round(elapsed, 1),
            "status": "EXCEPTION",
            "error": str(e),
        }


def result_from_summary_cache(trial, trial_idx, total, summary_path):
    """Rebuild a result dict from an existing per-trial summary JSON."""
    name = trial["name"]
    gt_hr = trial["gt_hr"]
    gt_lo = trial["gt_ci_lower"]
    gt_hi = trial["gt_ci_upper"]
    area = trial.get("area", "unknown")

    print(f"\n[{trial_idx}/{total}] {name} ({area})")
    print(f"  PDF: {trial['pdf'][:65]}...")
    print(f"  Ground Truth: HR={gt_hr} [{gt_lo}, {gt_hi}]")
    print(f"  Resume cache: {summary_path.name}")

    with open(summary_path, "r", encoding="utf-8") as f:
        cached = json.load(f)

    ext_hr = cached.get("hr")
    ext_lo = cached.get("ci_lower")
    ext_hi = cached.get("ci_upper")
    hr_method = cached.get("hr_method")
    elapsed = float(cached.get("processing_time_s") or 0.0)
    ipd_records = int(cached.get("total_ipd_records") or 0)
    n_curves_found = cached.get("n_curves_found")
    warnings = cached.get("warnings") or []

    if ext_hr is None:
        msg = warnings[0] if warnings else "Missing hr in cached summary"
        print(f"  Cached FAILED: {msg}")
        print(f"  Time: {elapsed:.1f}s  IPD: {ipd_records}")
        return {
            "name": name,
            "pdf": trial["pdf"],
            "area": area,
            "gt_hr": gt_hr,
            "ext_hr": None,
            "within_ci": False,
            "error_under_10pct": False,
            "time_s": round(elapsed, 1),
            "status": "FAIL_EXTRACT",
            "error": msg,
        }

    within_ci = gt_lo <= ext_hr <= gt_hi

    recip_hr = None
    within_ci_recip = False
    if trial.get("hr_source") == "derived" and ext_hr > 0:
        recip_hr = 1.0 / ext_hr
        within_ci_recip = gt_lo <= recip_hr <= gt_hi

    if gt_hr == 0:
        rel_error = float("inf") if ext_hr != 0 else 0.0
        orientation = "direct"
        final_hr = ext_hr
    elif not within_ci and within_ci_recip:
        rel_error = abs(recip_hr - gt_hr) / gt_hr * 100
        orientation = "reciprocal"
        final_hr = recip_hr
    else:
        rel_error = abs(ext_hr - gt_hr) / gt_hr * 100
        orientation = "direct"
        final_hr = ext_hr

    within_ci_final = gt_lo <= final_hr <= gt_hi
    status = "PASS" if within_ci_final else "FAIL"
    error_ok = rel_error < 10.0

    ci_str = (f"[{ext_lo:.3f}, {ext_hi:.3f}]"
              if ext_lo is not None and ext_hi is not None
              else "[N/A]")
    print(f"  Cached: HR={ext_hr:.3f} {ci_str}")
    if orientation == "reciprocal":
        print(f"  Reciprocal: HR={recip_hr:.3f} (better match)")
    print(f"  Rel Error: {rel_error:.1f}% {'OK' if error_ok else '>10%'}")
    print(f"  Within CI: {within_ci_final} -> {status}")
    print(f"  Method: {hr_method}")
    print(f"  Time: {elapsed:.1f}s  IPD: {ipd_records}")

    return {
        "name": name,
        "pdf": trial["pdf"],
        "area": area,
        "gt_hr": gt_hr,
        "gt_ci": [gt_lo, gt_hi],
        "ext_hr": ext_hr,
        "ext_ci": [ext_lo, ext_hi],
        "final_hr": final_hr,
        "orientation": orientation,
        "rel_error_pct": round(rel_error, 2),
        "within_ci": within_ci_final,
        "error_under_10pct": error_ok,
        "ipd_records": ipd_records,
        "time_s": round(elapsed, 1),
        "status": status,
        "n_curves_found": n_curves_found,
        "hr_method": hr_method,
    }


def print_summary(results, subset_name, subset_results):
    """Print summary table for a subset of results."""
    n = len(subset_results)
    n_extracted = sum(1 for r in subset_results
                      if r["status"] not in ("FAIL_EXTRACT", "EXCEPTION"))
    n_within_ci = sum(1 for r in subset_results if r.get("within_ci", False))
    n_under_10 = sum(1 for r in subset_results if r.get("error_under_10pct", False))
    errors = [r["rel_error_pct"] for r in subset_results
              if r.get("rel_error_pct") is not None]
    mean_error = sum(errors) / len(errors) if errors else 0
    if errors:
        se = sorted(errors)
        mid = len(se) // 2
        median_error = (se[mid - 1] + se[mid]) / 2.0 if len(se) % 2 == 0 else se[mid]
    else:
        median_error = 0

    print(f"\n  {subset_name} ({n} trials):")
    print(f"    Extracted:   {n_extracted}/{n}")
    print(f"    Within CI:   {n_within_ci}/{n}")
    print(f"    Error <10%:  {n_under_10}/{n}")
    print(f"    Mean Error:  {mean_error:.1f}%")
    print(f"    Median Error:{median_error:.1f}%")

    # Failure categories
    cats = {}
    for r in subset_results:
        cat = categorize_result(r)
        cats.setdefault(cat, []).append(r["name"])
    if any(k != "PASS" for k in cats):
        for cat in ["MARGINAL", "FAIL_ACCURACY", "FAIL_EXTRACT", "TEXT_ONLY"]:
            if cat in cats:
                print(f"    {cat}: {cats[cat]}")

    return {
        "subset": subset_name,
        "n_trials": n,
        "n_extracted": n_extracted,
        "n_within_ci": n_within_ci,
        "n_under_10pct": n_under_10,
        "mean_error_pct": round(mean_error, 2),
        "median_error_pct": round(median_error, 2),
        "categories": {k: v for k, v in cats.items()},
    }


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Expanded corpus validation")
    parser.add_argument("--phase2-only", action="store_true",
                        help="Run only the 15 Phase 2 diverse trials")
    parser.add_argument("--cardio-only", action="store_true",
                        help="Run only the 12 cardio/metabolic trials")
    parser.add_argument("--original-only", action="store_true",
                        help="Run only the 13 original ablation trials")
    parser.add_argument("--phase4-only", action="store_true",
                        help="Run only Phase 4 trials (from JSON)")
    parser.add_argument("--all", action="store_true",
                        help="Run all trials: original + cardio + phase2 + phase4")
    parser.add_argument("--resume", action="store_true",
                        help="Reuse existing *_summary.json files in output dir")
    args = parser.parse_args()

    # UTF-8 stdout
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8',
                                      errors='replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8',
                                      errors='replace')

    # Load Phase 4 trials if needed
    phase4_trials = []
    if args.phase4_only or args.all:
        phase4_trials = load_phase4_trials()
        if not phase4_trials:
            print("ERROR: No Phase 4 trials loaded.")
            if args.phase4_only:
                sys.exit(1)

    # Select trial set
    if args.phase4_only:
        trials = phase4_trials
        label = f"{len(phase4_trials)} Phase 4 Trials (7 specialties)"
    elif args.phase2_only:
        trials = PHASE2_TRIALS
        label = "15 Phase 2 Diverse Trials"
    elif args.cardio_only:
        trials = CARDIO_TRIALS
        label = "12 Cardio/Metabolic Trials"
    elif args.original_only:
        trials = ORIGINAL_TRIALS
        label = "13 Original Ablation Trials"
    elif args.all:
        trials = ALL_TRIALS + phase4_trials
        label = (f"{len(ALL_TRIALS) + len(phase4_trials)} Trials "
                 f"(40 v1.4 + {len(phase4_trials)} Phase 4)")
    else:
        trials = ALL_TRIALS
        label = f"{len(ALL_TRIALS)} Trials (13 Ablation + 12 Cardio + 15 Diverse)"

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Verify all PDFs exist
    missing = []
    for trial in trials:
        pdf_path = get_pdf_path(trial)
        if not pdf_path.exists():
            missing.append(f"{trial['name']}: {pdf_path}")
    if missing:
        print(f"ERROR: Missing {len(missing)} PDFs:")
        for m in missing:
            print(f"  {m}")
        sys.exit(1)

    print("=" * 75)
    print(f"EXPANDED VALIDATION: {label}")
    print(f"Started: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 75)

    results = []
    total_start = time.time()
    total = len(trials)
    n_resumed = 0

    for i, trial in enumerate(trials, 1):
        stem = _safe_stem(trial["pdf"])
        summary_path = OUTPUT_DIR / f"{stem}_summary.json"

        if args.resume and summary_path.exists():
            try:
                result = result_from_summary_cache(trial, i, total, summary_path)
                results.append(result)
                n_resumed += 1
                continue
            except Exception as e:
                print(f"  Resume cache load failed: {e}")
                print("  Falling back to fresh extraction...")

        try:
            pipeline = KMPipeline(dpi=300, max_pages=12, n_per_arm=100)
            result = validate_trial(pipeline, trial, i, total)
        except Exception as e:
            print(f"\n[{i}/{total}] {trial['name']} ({trial.get('area', 'unknown')})")
            print(f"  PIPELINE INIT EXCEPTION: {e}")
            result = {
                "name": trial["name"],
                "pdf": trial["pdf"],
                "area": trial.get("area", "unknown"),
                "gt_hr": trial["gt_hr"],
                "ext_hr": None,
                "within_ci": False,
                "error_under_10pct": False,
                "time_s": 0.0,
                "status": "EXCEPTION",
                "error": f"pipeline_init: {e}",
            }
        results.append(result)

    total_elapsed = time.time() - total_start

    # -------------------------------------------------------------------
    # Overall Summary
    # -------------------------------------------------------------------
    print("\n" + "=" * 75)
    print("EXPANDED VALIDATION SUMMARY")
    print("=" * 75)

    # Overall stats
    overall = print_summary(results, "OVERALL", results)

    # By subset
    original_results = [r for r in results if r["area"] == "AF-ablation"]
    cardio_results = [r for r in results
                      if r["area"] not in ("AF-ablation",) and r["name"] not in
                      [t["name"] for t in PHASE2_TRIALS]]
    phase2_results = [r for r in results
                      if r["name"] in [t["name"] for t in PHASE2_TRIALS]]

    orig_stats = new_stats = p2_stats = None
    if original_results:
        orig_stats = print_summary(results, "Original Ablation", original_results)
    if cardio_results:
        new_stats = print_summary(results, "Cardio/Metabolic", cardio_results)
    if phase2_results:
        p2_stats = print_summary(results, "Phase 2 Diverse", phase2_results)

    # By therapeutic area
    areas = {}
    for r in results:
        a = r.get("area", "unknown")
        areas.setdefault(a, []).append(r)
    if len(areas) > 1:
        print("\n  By Therapeutic Area:")
        for area, area_results in sorted(areas.items()):
            n_ext = sum(1 for r in area_results
                        if r["status"] not in ("FAIL_EXTRACT", "EXCEPTION"))
            n_ci = sum(1 for r in area_results if r.get("within_ci"))
            errs = [r["rel_error_pct"] for r in area_results
                    if r.get("rel_error_pct") is not None]
            me = f"{sum(errs)/len(errs):.1f}%" if errs else "N/A"
            print(f"    {area:<18} {n_ext}/{len(area_results)} extracted, "
                  f"{n_ci}/{len(area_results)} within CI, mean err {me}")

    print(f"\n  Total Time: {total_elapsed:.0f}s ({total_elapsed/60:.1f} min)")
    if args.resume:
        print(f"  Resumed from cache: {n_resumed}/{total} trials")

    # Per-trial table
    print(f"\n{'Trial':<22} {'Area':<14} {'GT HR':>6} {'Ext HR':>7} {'Err%':>6} "
          f"{'CI?':>4} {'Cat':>12} {'Method':>18} {'Time':>6}")
    print("-" * 105)
    for r in results:
        name = r["name"][:21]
        area = r.get("area", "?")[:13]
        gt = f"{r['gt_hr']:.2f}"
        fhr = r.get('final_hr') or r.get('ext_hr')
        ext = f"{fhr:.3f}" if fhr is not None else "N/A"
        err = f"{r['rel_error_pct']:.1f}" if r.get("rel_error_pct") is not None else "N/A"
        ci = "Y" if r.get("within_ci") else "N"
        cat = categorize_result(r)
        method = str(r.get("hr_method", ""))[:17]
        tm = f"{r['time_s']:.0f}s"
        print(f"{name:<22} {area:<14} {gt:>6} {ext:>7} {err:>6} "
              f"{ci:>4} {cat:>12} {method:>18} {tm:>6}")

    # -------------------------------------------------------------------
    # v1.4 Targets
    # -------------------------------------------------------------------
    n_total = len(results)
    n_extracted = overall["n_extracted"]
    n_within_ci = overall["n_within_ci"]

    pct_within_ci = n_within_ci / n_total * 100 if n_total > 0 else 0
    errors = [r["rel_error_pct"] for r in results
              if r.get("rel_error_pct") is not None]
    if errors:
        se = sorted(errors)
        mid = len(se) // 2
        median_err = (se[mid - 1] + se[mid]) / 2.0 if len(se) % 2 == 0 else se[mid]
    else:
        median_err = 999

    # Count distinct therapeutic areas with >= 1 PASS
    areas_with_pass = set()
    for r in results:
        if categorize_result(r) in ("PASS", "TEXT_ONLY"):
            areas_with_pass.add(r.get("area"))

    # v1.5 targets: 85%+ within CI, <5% median, 7+ areas
    # Versioned targets (v1.4 vs v1.5)
    is_v15 = n_total > 50
    ci_target = 85 if is_v15 else 80
    area_target = 7 if is_v15 else 5
    version = "v1.5" if is_v15 else "v1.4"

    print(f"\n  {version} TARGETS:")
    print(f"    {ci_target}%+ within CI:     {n_within_ci}/{n_total} = "
          f"{pct_within_ci:.1f}%"
          f" {'PASS' if pct_within_ci >= ci_target else 'FAIL'}")
    print(f"    Median error <5%:   {median_err:.1f}%"
          f" {'PASS' if median_err < 5 else 'FAIL'}")
    print(f"    {area_target}+ areas with PASS: {len(areas_with_pass)} "
          f"({sorted(areas_with_pass)})"
          f" {'PASS' if len(areas_with_pass) >= area_target else 'FAIL'}")

    # Known limitations
    known_failures = {"FREEZEAF-30M"}
    three_arm_trials = {t["name"] for t in trials if t.get("n_arms", 2) > 2}
    print(f"\n  Known limitations: {known_failures}")
    if three_arm_trials:
        print(f"  3-arm trials (may fail): {three_arm_trials}")

    all_targets_met = (pct_within_ci >= ci_target and median_err < 5
                       and len(areas_with_pass) >= area_target)
    print()
    if all_targets_met:
        print(f"VERDICT: PASS -- All {version} targets met")
    else:
        print(f"VERDICT: FAIL -- Not all {version} targets met (see above)")

    # -------------------------------------------------------------------
    # Save full report
    # -------------------------------------------------------------------
    report = {
        "validation": f"expanded_{n_total}_trials_{version}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "pipeline_version": "1.5" if is_v15 else "1.4",
        "total_time_s": round(total_elapsed, 1),
        "overall": overall,
        "original_ablation": orig_stats,
        "cardio_metabolic": new_stats,
        "phase2_diverse": p2_stats,
        "targets": {
            "within_ci_pct": round(pct_within_ci, 1),
            "within_ci_target": ci_target,
            "median_error_pct": round(median_err, 1),
            "median_error_target": 5,
            "n_areas_with_pass": len(areas_with_pass),
            "areas_target": area_target,
            "all_met": all_targets_met,
        },
        "verdict": "PASS" if all_targets_met else "FAIL",
        "trials": results,
    }
    report_path = OUTPUT_DIR / "expanded_report.json"
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, default=str)
    print(f"\nFull report: {report_path}")


if __name__ == '__main__':
    main()
